def filter_symbols(line):
    symbols = [
        "!",
        "@",
        "#",
        "$",
        "%",
        "^",
        "&",
        "*",
        "*",
        "(",
        ")",
        "-",
        "_",
        "+",
        "=",
        "§",
        "±",
        "[",
        "]",
        "{",
        "}",
        ";",
        ":",
        '"',
        "|",
        "/",
        "?",
        ">",
        ".",
        "<",
        ",",
    ]
    for symbol in symbols:
        line = line.replace(symbol, '')
    return line
